---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    components.backstage.egencia.com/pipeline-enabled: 'true'
    components.backstage.egencia.com/track-platform-compliance: 'true'
    github.com/project-slug: Egencia/travelfusion-pad-service
    pagerduty.com/service-id: ZZZZZZZ
    pagerduty.com/account: datadog
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
      - url: https://admin.example-org.com
      title: Wiki
      icon: backstage
      type: admin-dashboard
      - url: https://admin.example-org.com
      title: Jira
      icon: Jira
      type: admin-dashboard
      - url: https://admin.example-org.com
      title: Source
      icon: gitlab
      type: admin-dashboard
      - url: https://admin.example-org.com
      title: Runbook
      icon: confluence
      type: admin-dashboard
  description: Email handler service
  tags:
    - component
    - service
    - backstage
  name: email-handler
  dependsOn:
    - component:emailer
  system: email-platform
spec:
  lifecycle: Production
  owner: Communication
  type: service
