---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Egencia/travelfusion-pad-service
    pagerduty.com/service-id: P26LTN8
    pagerduty.com/account: datadog
  links:
    - url: https://app.datadoghq.com/dashboard/t5p-9gb-3k4/welcome-to-us1-dd-demo-11287?fromUser=false&refresh_mode=sliding&from_ts=1731344898026&to_ts=1731348498026&live=true
      title: Performance Dashboard
      icon: dashboard
      type: dashboard
    - url: https://backstage.core.shopist.org/docs/default/component/rollback
      title: Wiki
      icon: backstage
      type: admin-dashboard
    - url: https://shopist.atlassian.net/browse/DA
      title: Jira
      icon: Jira
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Source
      icon: gitlab
      type: admin-dashboard
    - url: https://shopist.atlassian.net/wiki/spaces/DA
      title: Runbook
      icon: confluence
      type: runbook
  description: Email handler service
  tags: ["framework:spring", "db:mysql"]
  name: email-handler
spec:
  lifecycle: Production
  tier: Tier 1
  owner: delivery-app
  type: service
  system: email-platform
  dependsOn:
    - component: emailer
    - component: email-service
