---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    components.backstage.egencia.com/pipeline-enabled: 'true'
    components.backstage.egencia.com/track-platform-compliance: 'true'
    github.com/project-slug: Egencia/travelfusion-pad-service
  description: This is a test, will delete soon
  tags:
    - component
    - service
    - backstage
  name: nick-test-backstage
spec:
  lifecycle: production
  owner: egencia-air-pampero
  type: service
